name: Build Android APK (Debug)

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install dependencies
        run: npm ci

      - name: Add Android platform (Capacitor)
        run: npx cap add android

      - name: Apply App Icon + Splash
        shell: bash
        run: |
          # Copy launcher icons
          cp -r assets/android-res/mipmap-* android/app/src/main/res/
          # Copy splash
          mkdir -p android/app/src/main/res/drawable
          cp assets/android-res/drawable/splash_screen.png android/app/src/main/res/drawable/splash_screen.png

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ADDON-S-Hawkeye-Pro-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
